name: Keep API Alive

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping API
        run: curl -s -o /dev/null -w "%{http_code}" https://tdssolver-n9xe.onrender.com/health